version: '3'
services:
  app:
    build:
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    depends_on:
      - db
    environment:
      DB_NAME: literacy-main
      DB_USER: postgres
      DB_PASSWORD: 1234
      DB_HOST: postgres
      TZ: "Asia/Seoul"
    restart: unless-stopped

  db:
    image: postgres:latest
    ports:
      - "5433:5432"
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: literacy-main
      TZ: "Asia/Seoul"
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: